npmScopes:
  fuks-ru:
    npmAuthToken: "${PERSONAL_NPM_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  styled-components@*:
    dependencies:
      react-is: "*"
  "@rtk-query/codegen-openapi@*":
    dependencies:
      lodash: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-3.2.3.cjs
