npmScopes:
  difuks:
    npmAuthToken: "${PERSONAL_NPM_TOKEN}"
    npmRegistryServer: "https://npm.pkg.github.com"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

pnpEnableEsmLoader: true

packageExtensions:
  styled-components@*:
    dependencies:
      react-is: "*"

yarnPath: .yarn/releases/yarn-3.2.3.cjs
