name: Build and deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      PERSONAL_NPM_TOKEN: ${{ secrets.PERSONAL_TOKEN }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PERSONAL_TOKEN }}
          fetch-depth: 0

      - name: Install modules
        run: yarn install

      - name: Build libs
        run: yarn build:lib

      - name: Eslint
        run: yarn lint

      - name: Build entries
        run: yarn build

      - name: Check packages versions
        run: yarn version check

      - name: Apply versions
        run: yarn version apply --all

      - name: Publish packages
        run: yarn workspaces foreach --include "@fuks-ru/{esenin-family-client}" --interlaced --verbose npm publish --tolerate-republish

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: |
            ci: Release packages
            
            [skip ci]

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Node build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/node/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/esenin-family-backend:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new

      - name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache

      - name: Nginx build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./.docker/nginx/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/esenin-family-nginx:latest

  pull-containers:
    name: Pull containers

    needs: build

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Remove docker images
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_NODE_USERNAME }}
          key: ${{ secrets.SSH_NODE_PRIVATE_KEY }}
          script: |
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/esenin-family-backend || true
            docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/esenin-family-nginx || true

      - name: Pull docker containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_NODE_USERNAME }}
          key: ${{ secrets.SSH_NODE_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/esenin-family-backend
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/esenin-family-nginx

  deploy:
    name: Deploy

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Stop containers
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_NODE_USERNAME }}
          key: ${{ secrets.SSH_NODE_PRIVATE_KEY }}
          script: |
            docker container stop esenin-family-backend || true
            docker container stop esenin-family-nginx || true
            docker container stop esenin-family-postgres || true
            docker rm esenin-family-backend || true
            docker rm esenin-family-nginx || true
            docker rm esenin-family-postgres || true

      - name: Run database
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_NODE_USERNAME }}
          key: ${{ secrets.SSH_NODE_PRIVATE_KEY }}
          script: |
            docker run --name ${{ env.POSTGRES_CONTAINER }} \
            --rm -d \
            -e POSTGRES_PASSWORD="${{ secrets.POSTGRES_PASSWORD }}" \
            -e POSTGRES_USER="${{ secrets.POSTGRES_USER }}" \
            -e POSTGRES_DB=esenin \
            -e PGDATA=/var/lib/postgresql/data/pgdata \
            -v "/server/esenin-family-backend/postgres/var":/var/lib/postgresql/data \
            --network="fuks-ru" \
            postgres:14.2-alpine

      - name: Run migrations
        uses: ./.github/actions/run-node
        with:
          secret-context: ${{ toJson(secrets) }}
          script: yarn prod:migration:run

      - name: Run node
        uses: ./.github/actions/run-node
        with:
          detached: true
          script: yarn prod

      - name: Sleep for wait node start
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Run nginx
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_NODE_USERNAME }}
          key: ${{ secrets.SSH_NODE_PRIVATE_KEY }}
          script: |
            docker run --name esenin-family-nginx \
            --rm -d \
            --network="fuks-ru" \
            difuks/esenin-family-nginx


  notification:
      name: Notification

      needs: [build, pull-containers, deploy]

      runs-on: ubuntu-latest

      if: always()

      steps:
        - name: Send telegram message
          uses: appleboy/telegram-action@master
          env:
            COMMIT_URL: ${{ github.server_url }}/${{ github.repository }}/commit/${{github.sha}}
            ACTION_URL: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}
          with:
            to: ${{ secrets.TELEGRAM_TO }}
            token: ${{ secrets.TELEGRAM_TOKEN }}
            format: markdown
            disable_web_page_preview: true
            message: |
              *esenin-family-backend*
              
              [build and deploy](${{ env.ACTION_URL }}) by *${{ github.actor }}*
              
              steps:
              build *${{ needs.build.result == 'success' && '✅' || '⛔️' }}*
              pull-containers *${{ needs.pull-containers.result == 'success' && '✅' || '⛔️' }}*
              deploy *${{ needs.deploy.result == 'success' && '✅' || '⛔️' }}*
              
              [commit](${{ env.COMMIT_URL }})
